const answerScreens = {
  STUDENT_ANSWER: 'STUDENT_ANSWER',
  TEACHER_ANSWER: 'TEACHER_ANSWER',
  PLAYGROUND: 'PLAYGROUND',
  LESSON_ACTIVITY: 'LESSON_ACTIVITY',
  TEST_LESSON_ACTIVITY: 'TEST_LESSON_ACTIVITY',
  TEST_PROBLEM: 'TEST_PROBLEM',
  TEST_TASK: 'TEST_TASK',
};

export default answerScreens;
